### ISSUE TITLE
请求是否有隐性等待

### ISSUE THREAD

**Issue by x6h0st** [boy-hack/hack-requests#5]
raw = '''
xxx
xxx
xxx

uname=123' OR SLEEP(5)-- &passwd=123&submit=Submit
'''
aa = hack.httpraw(raw)
print(aa.text())
报错信息：
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/HackRequests/HackRequests.py", line 231, in httpraw
    rep = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PyCharm/untitled/test.py", line 104, in <module>
    aa = hack.httpraw(raw)
  File "/usr/local/lib/python3.7/site-packages/HackRequests/HackRequests.py", line 233, in httpraw
    raise HackError("socket connect timeout")
HackRequests.HackRequests.HackError: socket connect timeout

**Comment by boy-hack** [comment]
如何复现？

**Comment by x6h0st** [comment]
HackRequests 可以获取网页的相应时间吗？

**Comment by boy-hack** [comment]
没有明白你的意思
